### PR TITLE
Add a winch handler

### PR DESCRIPTION
**Pull request by a5ob7r**
This patch adds a signal handler for the `winch`. Now, era can redraw contents of a timer and raindrops if the terminal window size is changed.

This movie is a demonstration of such a situation.

https://user-images.githubusercontent.com/12132068/162604510-31213502-e423-45f8-ac04-90377694f3fc.mp4

I'm new to JS/TS, so maybe there are some odd codes. Could you please review them? Thank you.

### CODE REVIEW

**Comment by kyoheiu** [comment]
Looks amazing!
But, the thing is I'm not familiar with OOP, which you are using in this PR I think. It may be a little bit too complicated for this simple tui app. I think there will be another way to deal with the window size in simpler or "scripting" way.

**Comment by a5ob7r** [comment]
Thank you for your review.

I don't know what is a "scripting" way you said. Does it mean a procedural way? However, I can understand that my way is probably too much complicated with OOP styles such as classes in this situation. So I remove them, is this good?

**Comment by kyoheiu** [comment]
Sorry for the vague expression: Yes, I meant procedural by 'scripting'.
Thank you for the refactoring. I tested your code, but it seems not to work on my environment (Linux, i3 window manager. Please see the gif). Could you tell me your environment?

Peek 2022-04-22 06-10

**Comment by a5ob7r** [comment]
This is my environment.

- OS: Linux
- WM: Xmonad
- Terminal: Alacritty
- Editor: Vim

**Comment by a5ob7r** [comment]
The shell prompt at the beginning of above your gif has showed `main` branch. Was the command really invoked on this PR?

**Comment by kyoheiu** [comment]
Sorry, my mistake. With catch_winch everything works fine! Thank you.

**Comment by a5ob7r** [comment]
Thank you for merging.

**Pull request merged**
